[package]
name = "HowlingInstall"
version = "0.1.0"
edition = "2024"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc" # Or whatever your cross-compiler is named

[dependencies]
terminal_size = "0.4" # Use the latest version