[package]
name = "Howling"
version = "0.1.0"
edition = "2024"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc" # Or whatever your cross-compiler is named

[dependencies]
libloading = "0.8.7"
serde = { version = "1.0.219", features=["derive"] }
serde_json = "1.0.140"
